### PR TITLE
Backfill Laradock

### PR DESCRIPTION
**Pull request by tom-on-the-internet**
can someone pull this down and make sure it works for them?

### CODE REVIEW

**Comment by john-humi** [comment]
> can someone pull this down and make sure it works for them?

Just getting started ..but right off the bat

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.workspace.ports is invalid: Port ranges don't match in length
services.workspace.ports is invalid: Port ranges don't match in length
services.workspace.ports is invalid: Port ranges don't match in length
services.tomcat.ports is invalid: Port ranges don't match in length
services.workspace.ports is invalid: Port ranges don't match in length
```

**Comment by tom-on-the-internet** [comment]
> > can someone pull this down and make sure it works for them?
> 
> Just getting started ..but right off the bat
> 
> ```
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.workspace.ports is invalid: Port ranges don't match in length
> services.workspace.ports is invalid: Port ranges don't match in length
> services.workspace.ports is invalid: Port ranges don't match in length
> services.tomcat.ports is invalid: Port ranges don't match in length
> services.workspace.ports is invalid: Port ranges don't match in length
> ```

Nice! Is that all of them?

**Comment by john-humi** [comment]
> > > can someone pull this down and make sure it works for them?
> > 
> > 
> > Just getting started ..but right off the bat
> > ```
> > ERROR: The Compose file './docker-compose.yml' is invalid because:
> > services.workspace.ports is invalid: Port ranges don't match in length
> > services.workspace.ports is invalid: Port ranges don't match in length
> > services.workspace.ports is invalid: Port ranges don't match in length
> > services.tomcat.ports is invalid: Port ranges don't match in length
> > services.workspace.ports is invalid: Port ranges don't match in length
> > ```
> 
> Nice! Is that all of them?

All i have so far, i think my .env just needs updating

**Review by kevinlanglois — APPROVED** [review]
works

**Pull request merged**
